Nama = ["Yusron", "Azzam", "Rakha", "Ken", "Onto"]
NilaiList = [90, 80, 70, 60, 50]
print("nama:", Nama[0], "nilai:", NilaiList[0])
print("nama:", Nama[1], "nilai:", NilaiList[1])
print("nama:", Nama[2], "nilai:", NilaiList[2])
print("nama:", Nama[3], "nilai:", NilaiList[3])
print("nama:", Nama[4], "nilai:", NilaiList[4])

if NilaiList[0] > 100:
    print("nilai tidak valid atau error")
elif NilaiList[0] == 100:
    print("nilai [0] A (lulus)")
elif NilaiList[0] >= 90:
    print("nilai [0] B (lulus)")
elif NilaiList[0] >= 80:
    print("nilai [0] C (lulus)")
elif NilaiList[0] >= 70:
    print("nilai [0] D (mengulang)")
elif NilaiList[0] < 60:
    print("nilai [0] E (mengulang)")

if NilaiList[1] > 100:
    print("nilai tidak valid atau error")
elif NilaiList[1] == 100:
    print("nilai [1] A (lulus)")
elif NilaiList[1] >= 90:
    print("nilai [1] B (lulus)")
elif NilaiList[1] >= 80:
    print("nilai [1] C (lulus)")
elif NilaiList[1] >= 70:
    print("nilai [1] D (mengulang)")
elif NilaiList[1] < 60:
    print("nilai [1] E (mengulang)")

if NilaiList[2] > 100:
    print("nilai tidak valid atau error")
elif NilaiList[2] == 100:
    print("nilai [2] A (lulus)")
elif NilaiList[2] >= 90:
    print("nilai [2] B (lulus)")
elif NilaiList[2] >= 80:
    print("nilai [2] C (lulus)")
elif NilaiList[2] >= 70:
    print("nilai [2] D (mengulang)")
elif NilaiList[2] < 60:
    print("nilai [2] E (mengulang)")

if NilaiList[3] > 100:
    print("nilai tidak valid atau error")
elif NilaiList[3] == 100:
    print("nilai [3] A (lulus)")
elif NilaiList[3] >= 90:
    print("nilai [3] B (lulus)")
elif NilaiList[3] >= 80:
    print("nilai [3] C (lulus)")
elif NilaiList[3] >= 70:
    print("nilai [3] D (mengulang)")
elif NilaiList[3] < 60:
    print("nilai [3] E (mengulang)")

if NilaiList[4] > 100:
    print("nilai tidak valid atau error")
elif NilaiList[4] == 100:
    print("nilai [4] A (lulus)")
elif NilaiList[4] >= 90:
    print("nilai [4] B (lulus)")
elif NilaiList[4] >= 80:
    print("nilai [4] C (lulus)")
elif NilaiList[4] >= 70:
    print("nilai [4] D (mengulang)")
elif NilaiList[4] < 60:
    print("nilai [4] E (mengulang)")


